// <auto-generated />
namespace GitHub.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class overrideconventionforgigsandgenres : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(overrideconventionforgigsandgenres));
        
        string IMigrationMetadata.Id
        {
            get { return "201809041018429_overrideconventionforgigsandgenres"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
